name: Build Zunivo Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      

      - name: Install dependencies
        run: npm install

      - name: Install Capacitor CLI
        run: npm install @capacitor/cli @capacitor/core @capacitor/android

      - name: Add Android platform
        run: npx cap add android

      - name: Copy web files
        run: npx cap copy android

      - name: Build Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Zunivo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
